data_root: /home/users/u103833/data
datasets:
- cora
- citeseer
- c-m10-m
- ogbn-arxiv
- pubmed
- wikics
- amazon-computers
- amazon-photo
- coauthor-cs
- coauthor-physics
- cora-full
- ogbn-products
- reddit
- roman-empire
- flickr
- actor
- chameleon
- squirrel
- amazon-ratings
models:
  baseline:
    enhanced_dim: 256
    epochs_phase1: 200
    epochs_phase2: 150
    joint_dim: 512
    lambda_align: 0.3
    lr_phase1: 0.01
    lr_phase2: 0.0001
    max_iterations: 20
    temperature: 0.1
  dbigcn:
    architecture:
      dropout: 0
      hidden_dim: 512
      n_neighbors: 2
    training:
      alpha: 1.0
      epochs: 10000
      loss_beta: 1.0
      lr: 0.0001
      patience: 100
      wd: 0.0001
  dgpn:
    architecture:
      K: 3
      beta: 0.7
      dropout: 0.5
    training:
      alpha: 1.0
      epochs: 10000
      lr: 0.001
      patience: 100
  icis:
    batch_size: 16
    classifier_epochs: 100
    classifier_lr: 0.0001
    cos_sim_loss: false
    embed_dim: 1000
    epochs: 1000
    lr: 0.0001
    num_layers: 3
    patience: 50
    wn_factor: 10.0
  zerog:
    R: 10
    batch_size: 2
    epochs: 50
    grad_accum: 4
    k: 2
    lr: 0.0001
    source:
    - Cora
    - Citeseer
    - Pubmed
    - Arxiv
    target:
    - Cora
    - Citeseer
    - Pubmed
models_to_run:
- dgpn
- dbigcn
- icis
- baseline
- zerog
seeds:
- 0
- 1
- 2
- 3
- 4
